version: '3.2'
services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
  movie-service:
    build:
      context: ./services/movie
      dockerfile: Dockerfile.test
    container_name: movie
    ports:
      - '9000:9000'
    environment:
      - JWT_SECRET=dbd5e5dc-f606-11ec-acd2-d32960984f38
      - DB_HOST=mongodb://mongo:27017/
      - DB_NAME=movies
      - DB_USER=
      - DB_PASS=
      - OMDB_BASE_URL=https://omdbapi.com
      - OMDB_API_KEY=${OMDB_API_KEY}
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - REDIS_PASSWORD=
      - NODE_ENV=test
    command: npm run test:integration
    depends_on:
      - redis

  auth-service:
    build:
      context: ./services/auth
      dockerfile: Dockerfile.test
    ports:
      - '8000:8000'
    environment:
      - JWT_SECRET=dbd5e5dc-f606-11ec-acd2-d32960984f38
      - MOVIE_API_URL=movie-service:9000
    command: npm run test:integration